export OPENAI_API_KEY=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
export PINECONE_API_KEY=87823627-c1f4-48fe-9c36-3d19d3dd29bb
export TRANSFORMERS_CACHE=/mnt/project/chatbotai/huggingface_cache/transformers
export HF_DATASETS_CACHE=/mnt/project/chatbotai/huggingface_cache/datasets

python TA_gradio_ux.py
