wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1668947345.789926
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      3:
      - 23
      4: 3.9.0
      5: 0.13.5
      6: 4.24.0
      8:
      - 5
